name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  get_it: ^8.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# Configuración de flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# Configuración de flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app_icon.png"
  android_12:
    image: "assets/app_icon.png"
    icon_background_color: "#FFFFFF"
  fullscreen: true
